name: PHPUnit for Hyperf

on: [ push, pull_request ]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }} Swoole ${{ matrix.swoole-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0' ]
        hyperf-version: [ '^2.2', '^3.0' ]
        exclude:
          - php-version: '7.4'
            hyperf-version: '^3.0'
      max-parallel: 5
    env:
      HF_VERSION: ${{ matrix.hyperf-version }}
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
          extensions: pdo, pdo_mysql, redis
      - name: Show Environment
        run: |
          php -v
          php -m
          php -i
      - name: Setup Packages
        run: |
          composer require "hyperf/utils: $HF_VERSION"
          composer update -o
      - name: Run Test Cases
        run: |
          vendor/bin/php-cs-fixer fix --dry-run
          composer analyse
          composer test
